# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: droidlinguist
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

# File Upload
multipart:
    maxFileSize: 5Mb
    maxRequestSize: 10Mb

# ===================================================================
# DroidLinguist specific properties
# ===================================================================

droidlinguist:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
